### ISSUE TITLE
night not working

### ISSUE THREAD

**Issue by koos147** [biddster/node-red-contrib-time-range-switch#11]
The "night" time gives "invalid date or time" all other functions are working fine

**Comment by biddster** [comment]
Not managed to recreate this one yet.

What version of nodejs, node-red and this node are you using?

**Comment by koos147** [comment]
hey,

I think i made some mistake. i have created a new flow and added all options possible to it. everything was working exectly as expected. an i am not able to reproduce it.

thanks anyway for the most usefull function of node-red 👍

**Comment by biddster** [comment]
No problem, glad this is of use.
