### ISSUE TITLE
Enhancement request: offset time on solar events

### ISSUE THREAD

**Issue by oakbrad** [biddster/node-red-contrib-time-range-switch#12]
Hi, thank you so much for this wonderful node! I am using it to control lighting in my smart home and it is really helpful.

I would love the ability to define the time range with an offset for the suncalc events. For example, set the start to sunset with an offset of -60 minutes would open the range one hour before that event.

This would allow a lot more flexibility to defining the range.

I noticed "bigtimer" has a solar offset if that's helpful, but that node is a lot different than yours.

**Comment by biddster** [comment]
Fixed in 0.5.0.

**Comment by oakbrad** [comment]
Wow thank you!!
