### ISSUE TITLE
0.5.0 not propagated to palette manager

### ISSUE THREAD

**Issue by vworp** [biddster/node-red-contrib-time-range-switch#13]
Palette manager still showing 0.4.0 as the most up to date version. Not sure where it gets its version from, is it https://flows.nodered.org/node/node-red-contrib-time-range-switch

**Comment by biddster** [comment]
It's really odd. libraries.io is showing 0.4.0 as well, which is where I think node-red get's its info. I've pinged libraries.io to update the package.

**Comment by biddster** [comment]
I republished 0.5.0 under a 0.5.1 release and that has woken everything up. Go grab 0.5.1.
