### ISSUE TITLE
invalid date

### ISSUE THREAD

**Issue by EmmanuelLM** [biddster/node-red-contrib-time-range-switch#14]
Hi, I am using time-range-switch 0.5.1 with node-red 0.18.7 on HomeAssistant (hassio).
Whenever I use the time-range switch, I get "invalid date - invalid date". Could you help me debug this?
My question is: where does the time-range-switch get its date time from?

**Comment by biddster** [comment]
Do you have a stack trace from your system log?

**Comment by Poodlepapa** [comment]
Did you solve this problem? I have the same issue and I think its making my flow not work properly.  Ive installed all three dependancies and still not luck
