### ISSUE TITLE
0.6.0 "TypeError: moment.twix is not a function"

### ISSUE THREAD

**Issue by cbulock** [biddster/node-red-contrib-time-range-switch#19]
Since upgrading to the newest version, none of my flows using this node have been working.

Showing "TypeError: moment.twix is not a function" in the logs.  Tried reinstalling via NPM.  Switching back to 0.5.1 corrected the issue

**Comment by biddster** [comment]
Thanks for the report @cbulock. It's an odd one as all the tests pass here and work fine.

What version of nodejs and node-red are you using?

**Comment by Unpuertomex** [comment]
I'm having the same issue with my nodes, every one of them is showing "TypeError: moment.twix is not a function". How do you switch back to 0.5.1?

nodejs - v8.11.2
node-red - v0.18.7

**Comment by cbulock** [comment]
I'm using the nodered/node-red-docker:v8 docker container for NodeRed.

nodejs: v8.11.2
node-red: 0.18.7

**Comment by cbulock** [comment]
@Unpuertomex you can switch back to an older version by running `npm install node-red-contrib-time-range-switch@0.5.1`

**Comment by Unpuertomex** [comment]
@cbulock thank you that did the trick

**Comment by Azburkabas** [comment]
Hi, just to report i too have the same issues with 0.6.0.
 Node-RED version: 0.18.7
  node.js version: 8.11.3
  npm version: 6.2.0
  Platform/OS: Ubuntu 17.10

Reverting to 0.5.1 helps.

**Comment by biddster** [comment]
I've just released 0.6.1 with a potential fix, let me know how you get on.

**Comment by cbulock** [comment]
Sorry for the delay on testing this out.  Upgraded yesterday, and after a day of use, everything is looking good on my end.

**Comment by TerryLansdown** [comment]
Hi, no luck with 0.6.1. I'm on Node-red version 6.5.0. 

Tried v 0.5.1, no luck with that either getting 'TypeError: moment.twix is not a function'.

Sorry.

**Comment by biddster** [comment]
Apologies @TerryLansdown, at a bit of a loss at the moment. I'll continue to investigate.

**Comment by TerryLansdown** [comment]
No problem, very much appreciate the effort!

**Comment by biddster** [comment]
@TerryLansdown can you confirm your node-red and nodejs versions please? From the above I'm assuming you're using nodejs 6.5.0 as there's no node-red version corresponding to that. E.g. I'm using 0.19.4.

**Comment by TerryLansdown** [comment]
Hi, aplogies. I’ve moved on. I’m using Bigtimer+ now. I hope you can get things worked out.
