### ISSUE TITLE
Hardcoded times does not work 

### ISSUE THREAD

**Issue by leeiberry** [biddster/node-red-contrib-time-range-switch#20]
i have set the time range for 13:00 to 16:00 
current Local time is 12:30 
i get a negative return ( ie output 2)  OK 
change the time range to 12:15 - 16:00 
current time is still 12:30 
i get a negative return ( ie output 2)  NOT OK 

No output from Output 1 (positive) with different compo of times 

my location is UTC + 8   and in the southern hemisphere  (australia) 
could this is an issue  ?

**Comment by biddster** [comment]
@leeiberry, I think this has been fixed in 0.6.1. Please can you give that a test and let me know?

**Comment by leeiberry** [comment]
thanks @biddster  that has fixed it :)
