### ISSUE TITLE
question about start/end times that cross with the seasons

### ISSUE THREAD

**Issue by rhd** [biddster/node-red-contrib-time-range-switch#22]
Hi,

Thanks for this great little node. I have a question.

Say I want my lights to come on at `6am - sunrise`. What happens if `sunrise` happens before `6am` as it does in the summer time? In this case, I'd like to **not** have the lights come on at all.

Thanks!

**Comment by biddster** [comment]
@rhd I think this can be solved by having an inject node that fires at 6am. That's wired into time-range-switch which has a range from 1am (or any time that will always be before sunrise) until sunrise. Connect the lights to output 1 and output 2 to nothing. If 6am is after sunrise, time-range-switch will send to output 2 and nothing will happen. I have the exact same arrangement for my porch light.

**Comment by rhd** [comment]
@biddster thanks. That is how I ended up solving it. I guess this is more of an issue for `schedex`. It would be really nice if there was a checkbox that said `don't fire if start time is before end time`. Thanks for the great plugins... I'm going to close this issue.

**Comment by rhd** [comment]
![image](https://user-images.githubusercontent.com/3422847/56559904-d284f600-6557-11e9-86f2-08271f855baf.png)

My final solution didn't use `time-range-switch` - it used `schdex` to fire the events and the `sun` state in homeassistant to check to see if the sun was above or below the horizon. This could have been a `time-range-switch` instead.
