### ISSUE TITLE
Wrong label of outputs

### ISSUE THREAD

**Issue by Jarod2801** [biddster/node-red-contrib-time-range-switch#27]
Looks like the labels of the outputs are switched.
If the current time falls within the range specified the message is forwarded to "output 2".
Output 2 is labelled with "within".

**Comment by biddster** [comment]
Thanks for the report. 

If the current time falls within the range specified, the message goes to output 1 and that is labelled "within". 

Are you saying that messages are going to the wrong outputs?

If so, please can you let me know the version of node red you're using and the version of this node you're using? 

What timezone are you in?

**Comment by biddster** [comment]
Oh, I can see you're in Germany.

**Comment by Jarod2801** [comment]
Hi,

looks like I made an error with the TZ.
Retried it some minutes ago.

Everything works like expected.

![image](https://user-images.githubusercontent.com/10256277/72193684-d8cf4100-340a-11ea-8a7e-0e89bc324b64.png)

Sorry for the confusion.

**Comment by biddster** [comment]
No problem at all. Bug reports are always welcome.
