### ISSUE TITLE
v1.1.3 not available in Node-Red palette

### ISSUE THREAD

**Issue by ptweety** [biddster/node-red-contrib-time-range-switch#53]
Hi @biddster,

I noticed that your latest version (v.1.1.3) of `node-red-contrib-time-range-switch` is not available vie Node-Red -> Palette. Instead only v1.1.2 is visible. `npm outdated` shows the same:

```
$ npm outdated
Package                             Current  Wanted  Latest  Location                                         Depended by
node-red-contrib-time-range-switch    1.1.2   1.1.3   1.1.3  node_modules/node-red-contrib-time-range-switch  data
```

**Comment by biddster** [comment]
Oh, that's odd. I'll look into it. Thank you.

**Comment by ptweety** [comment]
Well, it turns out that on https://flows.nodered.org/node/node-red-contrib-time-range-switch any registered user can request an update of any node. After I did this the next run of https://github.com/node-red/flow-library/actions picked your node and updated it ...

**Comment by biddster** [comment]
Thank you
