### ISSUE TITLE
Seconds support?

### ISSUE THREAD

**Issue by bigfeetneedbigboots** [biddster/node-red-contrib-time-range-switch#54]
Thanks for your work on this node - I love it!

I set the config of this node both programatically and with fixed config depending on what I'm doing. I have tested and found the node doesn't support seconds. Whilst it does allow seconds to be specified (e.g. 12:34:56), it disregards them and effectively "rounds down" (i.e. 12:34:00).

My request is for this node to support seconds. 

The main reason I am asking is so I can handle use cases where users want something to stay on and they set the config accordingly. If the node supported seconds, I could set the start time to 00:00 (which already works) and the finish time to 23:59:59. Currently if I do this, the 2nd output is used for the last minute of the day.

Thank you for considering my request.

**Comment by biddster** [comment]
Fixed in 1.2.0
