### ISSUE TITLE
day switch

### ISSUE THREAD

**Issue by Vebryn** [biddster/node-red-contrib-time-range-switch#6]
Hi,

Awesome module, so useful with my Home Automation !

Is it possible to add check boxes to test day of week ? Monday, tuesday, etc.

Best regards.

**Comment by biddster** [comment]
Many thanks, glad you like it. 

Ironically, I don't actually use it. I wrote it for my dad so his stairs would only operate during the dark. I.e. he could filter out incoming 433Mhz sensor messages during the day.

Let me think about day support. Where ranges fall between 00:00 and 23:59, the behaviour is pretty clear cut. 

Where a range falls over a day boundary, what would we do? Guess it's automatically output 2?

**Comment by Vebryn** [comment]
Interesting! I notice that inject node is able to schedule a payload send.
Idea is to integrate day select into time-range-switch.

**Comment by Vebryn** [comment]
Futhermore, inject node is working well with sun event node! So I think no change is needed :)

**Comment by fdattein** [comment]
For weekdays you may want to try:
http://tech.scargill.net/node-red-scheduler/
