### ISSUE TITLE
Enhancement request: Take time fields from data

### ISSUE THREAD

**Issue by TotallyInformation** [biddster/node-red-contrib-time-range-switch#9]
Hi, a really handy upgrade to this node would be to allow the input fields for the times to come from somewhere other than just manually input.

If you look at a number of the core nodes now, they allow input to be manually entered (as yours does right now) or to come from msg.<something>, flow.<something>, global.<something>

This would allow the times to be picked up from the input msg or a context variable.

The inject node contains the appropriate code to use.

**Comment by biddster** [comment]
Thanks for the note - I think this would be useful across all of the nodes I've written.

**Comment by cflurin** [comment]
Hi, 
I'd like to store all my parameters in a config.json file or to use `node-red-contrib-config`.
I'll also appreciate this feature.

**Comment by ghost** [comment]
This looks to be the only timing plugin that does what i need, except support for fields.

I already took a closer look at the core plugins of node red. This plugins parse their data from the message only, whats quite easy to implement. I think this requires a function node in front to prepare the data.
e.g.: https://github.com/node-red/node-red-nodes/blob/master/social/email/61-email.js

I also found one Plugin, that is more complex and can parse data from the message, flow or from global.
(node-red-contrib-home-assistant-websocket)

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/blob/a0fdb963b0a1ac598773dfc3e7ea8848ae054bef/lib/mustache-context.js

There you enter {{global.fieldName}}, {{flow.flowFieldName}} or {{msg.payload}} into the textbox and the data is parsed.

I would prefer the last solution. @biddster, whats your opinion on this topic?

**Comment by ghost** [comment]
It was not to hard to implement a quick and dirty prototype with the second solution:
https://github.com/huzergackl/node-red-contrib-time-range-switch/commit/317875ddeb6c57d674b1df67b8ab4d95785bcaef

At the moment it is without proper null checks and without unit tests. But ill do further testing and cleanup before creating an pr.

**Comment by biddster** [comment]
Closing as implemented in fork.
